#!/bin/sh
if test "$1" = "--ask"
then
apt-get install $2
elif test "$1" = "--sync"
then
apt-get update
elif test "$1" = "--search"
then
apt-cache search $1
elif test "$1" = "--update"
then
apt-get update && apt-get upgrade
elif test "$1" = "--unmerge"
then
apt-get remove $2
else
echo E: Invalid operation $1
fi
