#!/bin/sh

if test "$1" = "install"
 then
apt-get install $2
elif test "$1" = "update"
then
apt-get update
elif test "$1" = "upgrade"
then
apt-get install $2
elif test "$1" = "info"
then
apt-cache show $2
elif test "$1" = "search"
then
apt-cache search $2
elif test "$1" = "remove"
then
apt-get purge $2
else
echo E: Invalid operation $1
fi


