#!/bin/sh

if test "$1" = "install"
 then
pacman -S $2
elif test "$1" = "update"
then
pacman -Sy
elif test "$1" = "upgrade"
then
pacman -S $2

elif test "$1" = "info"
then
pacman -Si $2
elif test "$1" = "search"
then
pacman -Ss $2
elif test "$1" = "remove"
then
pacman -Rs $2
else
echo E: Invalid operation $1
fi
