#!/bin/sh
install() {
if test "$1" = "--reinstall"
then
apt-get remove $2
apt-get install $2
else
apt-get install $1
}

if test "$1" = "install"
then
install $2 $3
elif test "$1" = "update"
then
apt-get update

elif test "$1" = "info"
then
apt-cache show $2
elif test "$1" = "upgrade"
then
apt-get upgrade

elif test "$1" = "remove"
then
apt-get purge $2
else
echo E: Invalid operation $1
fi

